pipelines:
  default:
    - step:
        name: Set Up Python Environment
        image: python:3.10
        cache:
          - .cache/pip
        commands:
          - python3 -m pip install --upgrade pip
          - pip install -r requirements.txt
          - chmod +x sklate.py
          - ls -l  # Check if the file exists
          - python3 sklate.py
